name: safepay_checkout
description: A simple and easy-to-integrate Flutter package for Safepay Checkout.
version: 1.0.4
homepage: https://github.com/Asad-Shafique/safepay-checkout

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  http: ^1.2.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  assets:
    - assets/
